version: '3'
services:
    db:
        image: mysql
        container_name: mysql-kun
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        ports:
            - "3306:3306"
